dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
addons:
   sonarcloud:
      organization: $SONAR_ORGANIZATION
      token: $SONAR_TOKEN
script:
   # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AlefMeira_Bookstoremanager
cache:
   directories:
      - $HOME/.m2
      - $home/.sonar/cache
before_install:
   - chmod +x mvnw
    
